# Introduction

NumPy, short for Numerical Python, is an __important__ package for scientific computing in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures. NumPy is highly efficient and allows for operations on large datasets with ease, making it an essential tool for scientific research.

In the context of Physics research, NumPy is particularly useful for the following reasons:

1. **Array Operations**: NumPy's array objects are more efficient and convenient than Python's built-in lists for numerical computations.
2. **Mathematical Functions**: It includes a wide range of mathematical functions that are essential for physics calculations, such as linear algebra, Fourier transforms, and random number generation.
3. **Data Handling**: NumPy can handle large datasets, which is common in physics experiments and simulations.
4. **Interoperability**: It integrates well with other scientific computing libraries like SciPy, Matplotlib, and Pandas, providing a comprehensive ecosystem for data analysis and visualization.

At the heart of NumPy lies the __ndarray__ object, which represents multidimensional arrays.

For beginners in Physics research, learning NumPy can significantly enhance their ability to perform complex calculations, analyze experimental data, and visualize results effectively.

# Introduction to Arrays

## What are NumPy Arrays?

Arrays are a fundamental data structure in programming that allow you to store multiple values in a single variable. They are particularly useful for handling collections of data that need to be processed in a uniform manner. In Python, arrays are commonly referred to as lists, but NumPy provides a more efficient and powerful alternative called NumPy arrays or `ndarrays`.

NumPy arrays, or `ndarrays`, are a powerful feature of the NumPy library in Python. They provide a more efficient and convenient way to handle large datasets compared to Python's built-in lists. Here are some key characteristics of NumPy arrays:

1. **Homogeneous Data**: All elements in a NumPy array are of the same data type, which allows for efficient memory usage and faster computations.
2. **Multidimensional**: NumPy arrays can have multiple dimensions, making them ideal for representing matrices and other higher-dimensional data structures. Dimensions refer to the number of indices required to locate an element within the array. For example, a 1D array has one dimension, a 2D array has two dimensions, and so on. In the context of linear algebra, a 2D array represents a matrix, while in programming terms, it can be thought of as a list of lists.
3. **Vectorized Operations**: NumPy allows you to perform element-wise operations on arrays without using loops, making your code shorter and easier to read.
4. **Broadcasting**: NumPy arrays support broadcasting, a feature that allows you to perform arithmetic operations on arrays of different shapes in a flexible manner.
5. **Integration with Other Libraries**: NumPy arrays form the backbone of many other scientific computing libraries in Python, including Pandas and Matplotlib (which we’ve already discussed) and SciPy (which we’ll touch on briefly later).


## Creating NumPy Arrays

Creating arrays is the first step to using NumPy for scientific computing. NumPy provides several functions to create arrays of different shapes and types, filled with different values.

Here are some common ways to create NumPy arrays:

1. **From Python Lists**: You can create a NumPy array from a Python list or tuple using the `np.array()` function. This is useful when you have existing data in a list or tuple format that you want to convert to a NumPy array.

2. **Using Built-in Functions**: NumPy provides several built-in functions to create arrays with specific values:
    - `np.zeros(shape)`: Creates an array filled with zeros. The `shape` parameter specifies the dimensions of the array.
    - `np.ones(shape)`: Creates an array filled with ones. The `shape` parameter specifies the dimensions of the array.
    - `np.arange(start, stop, step)`: Creates an array with a range of values from `start` to `stop` (exclusive) with a given `step`.
    - `np.linspace(start, stop, num)`: Creates an array with `num` evenly spaced values between `start` and `stop` (inclusive).

3. **Random Arrays**: NumPy also provides functions to create arrays with random values, which are useful for simulations and testing:
    - `np.random.rand(d0, d1, ..., dn)`: Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1).
    - `np.random.randn(d0, d1, ..., dn)`: Creates an array of the given shape and populates it with random samples from a standard normal distribution (mean 0, variance 1).

4. **Identity and Diagonal Arrays**: For linear algebra operations, you might need identity matrices or diagonal matrices:
    - `np.eye(N)`: Creates a 2D array with ones on the diagonal and zeros elsewhere (identity matrix).
    - `np.diag(v)`: Creates a 2D array with the elements of `v` on the diagonal and zeros elsewhere.

By using these functions, you can create arrays that suit your specific needs for data analysis, simulations, and other scientific computations.

In [5]:
import numpy as np

# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

# Creating an array of zeros
array_zeros = np.zeros((3, 3))
print("Array of Zeros:\n", array_zeros)

# Creating an array of ones
array_ones = np.ones((2, 4))
print("Array of Ones:\n", array_ones)

# Creating an array with a range of values
array_range = np.arange(10, 20)
print("Array with Range of Values:", array_range)

# Creating an array with evenly spaced values
array_linspace = np.linspace(0, 1, 5)
print("Array with Evenly Spaced Values:", array_linspace)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with Range of Values: [10 11 12 13 14 15 16 17 18 19]
Array with Evenly Spaced Values: [0.   0.25 0.5  0.75 1.  ]


## Reshaping Arrays

Reshaping arrays is an important operation in NumPy that allows you to change the shape of an existing array without altering its data. This is particularly useful when you need to perform matrix operations or simply reorganize data for better readability.

### Reshaping with `reshape()`

The `reshape()` function in NumPy allows you to change the shape of an array. The new shape must be compatible with the original shape, meaning the total number of elements must remain the same.

For example, you can reshape a 1D array into a 2D array:

In [6]:
# Reshaping an array

# Creating a 1D array
array_1d = np.arange(1, 10)

# Reshaping the 1D array to a 2D array
array_2d = array_1d.reshape(3, 3)

print("1D Array:\n", array_1d)

print("2D Array:\n", array_2d)

1D Array:
 [1 2 3 4 5 6 7 8 9]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing and Slicing

Indexing and slicing are fundamental operations for accessing and manipulating elements in NumPy arrays. These operations allow you to retrieve specific elements, rows, columns, or subarrays from a larger array. Understanding how indexing and slicing work is essential for working with NumPy arrays effectively.

### Indexing

Indexing in NumPy works similarly to indexing in Python lists, but with additional capabilities for multidimensional arrays. You can use square brackets `[]` to access individual elements or slices of an array. The key points to remember are:

1. **Indexing Starts at 0**: The index of the first element in an array is 0, not 1.
2. **Negative Indexing**: You can use negative indices to access elements from the end of the array.
3. **Multidimensional Indexing**: In multidimensional arrays, you can use a tuple of indices to access elements along each axis. For example, in a 2D array, array[i, j] retrieves the element located at row i and column j.

#### 1D Array Indexing

For a 1D array, you can access elements using their index positions:

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) # Output: 1
print(arr[-1]) # Output: 5

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d[0, 0]) # Output: 1
print(array_2d[1, 2]) # Output: 6
print(array_2d[1, -1]) # Output: 6

1
5
1
6
6


### Slicing

Slice notation in NumPy allows you to extract subarrays from an array by specifying a range of indices. Slicing is a powerful feature that enables you to work with subsets of data without copying the original array. The basic syntax for slicing is `start:stop:step`, where `start` is the starting index, `stop` is the stopping index (exclusive), and `step` is the step size.

In [12]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Slicing the array
sliced_array = array_2d[0, 0:2]
print(sliced_array) # Output: [1 2]

sliced_array = array_2d[1, 1:]
print(sliced_array) # Output: [5 6]

sliced_array = array_2d[:, 1]
print(sliced_array) # Output: [2 5]

[1 2]
[5 6]
[2 5]


💡 Notice in the last example that to access the second column of a 2D array, you can use `print(array[:, 1])`, which retrieves all rows of the second column. Similarly, to access the second row, you can use `print(array[1, :])`, which retrieves all columns of the second row.